### ISSUE TITLE
Fix for Linux platform

### ISSUE THREAD

**Issue by MatheusSalomao** [CViniciusSDias/php-text-to-speech#2]
Hello,
the code for linux has a typo.
https://github.com/CViniciusSDias/php-text-to-speech/blob/1ce66573680deeec5d30ee0cc212e9776142a22c/src/factory.php#L12

Apparently, absence of the output parameter is causing segmentation fault.
https://github.com/CViniciusSDias/php-text-to-speech/blob/1ce66573680deeec5d30ee0cc212e9776142a22c/src/Platforms/Linux/SpdSayLinuxSpeaker.php#L13

_The segmentation fault occurred using PHP 8.0.2 (cli) (built: Feb 23 2021 15:14:40) ( NTS )_

**Comment by CViniciusSDias** [comment]
Hello, Matheus.

I'm unable to reproduce this issue but could you please confirm if b0401aafb14fa75b1a4fc8332775471ad74652d3 fixes it?

**Comment by MatheusSalomao** [comment]
I still have the error.
![speak_segmentation_fault_3](https://user-images.githubusercontent.com/16800862/109375736-0e442180-788d-11eb-8080-c41888fc11cf.png)

**Comment by CViniciusSDias** [comment]
Since I'm not able to reproduce the issue, do you mind providing more details about your env?

Which distro is it? Are you able to debug the code? Do you have spd-say and/or espeak installed? Are you running php directly or via some kind of container?

Thanks in advance.

**Comment by MatheusSalomao** [comment]
**Which distro is it?**
_OS: Pop 20.10 groovy
Kernel: x86_64 Linux 5.8.0-7642-generic_

**Do you have spd-say and / or espeak installed?**
_Yes, both._

**Are you running php directly or via some kind of container?**
_I am running php directly and also through the official PHP container._

I can reproduce the error with the following code: https://3v4l.org/n9cuS
note the error is not reproduced when the xdebug extension is enabled. ¯\\_(ツ)_/¯

**Comment by CViniciusSDias** [comment]
Wow. Looks like you found a PHP bug.
haha

I just pushed a fix and I will also file this bug in the PHP core's bug tracker. Let me know if a composer update fixes it and if it does I'll close this issue.

**Comment by CViniciusSDias** [comment]
https://bugs.php.net/bug.php?id=80811

**Comment by MatheusSalomao** [comment]
Wow, this is great.
I never thought I would be able to contribute anything to the language ... it was a bug, but it is something hahaha.
**Thanks!**

**Comment by CViniciusSDias** [comment]
Haha
That's definitely something. So, did it work now? Can I close this issue?

**Comment by MatheusSalomao** [comment]
Yes, of course. 
Bye
